- name: kill running erlang processes
  shell: "pkill -f beam"
  ignore_errors: yes

- name: create amoc directory
  file: dest={{ install_dir }} mode=755 state=directory

- name: unarchive amoc tarball remotely
  unarchive: src=../_build/default/rel/amoc/amoc-0.9.tar.gz dest={{ install_dir }}

- name: template configuration
  template: src=app.config.j2 dest={{ install_dir }}/releases/0.9/sys.config

- name: template vm.args
  template: src=vm.args.j2 dest={{ install_dir }}/releases/0.9/vm.args
