x-amoc-defaults: &amoc-defaults
  image: "amoc:latest"
  networks:
    - amoc-test-network
  volumes:
    - type: bind
      source: ./extra_code_paths
      target: /extra_code_paths
  environment:
    AMOC_NODES: "['amoc@amoc-master']"
  healthcheck:
    test: "amoc status"

services:
  amoc-master:
    <<: *amoc-defaults
    hostname: "amoc-master"
    environment:
      AMOC_EXTRA_CODE_PATHS: '["/extra_code_paths/path1", "/extra_code_paths/path2"]'
  amoc-worker-1: &amoc-worker
    <<: *amoc-defaults
    hostname: "amoc-worker-1"
  amoc-worker-2:
    <<: *amoc-defaults
    hostname: "amoc-worker-2"
  amoc-worker-3:
    <<: *amoc-defaults
    hostname: "amoc-worker-3"
networks:
  amoc-test-network:
