x-amoc-defaults: &amoc-defaults
  build:
    context: ../
    dockerfile: Dockerfile
  networks:
    - amoc-test-network
  volumes:
    - type: bind
      source: ./extra_code_paths
      target: /extra_code_paths
  environment:
    AMOC_NODES: "['amoc@amoc-master']"
    AMOC_EXTRA_CODE_PATHS: '["/extra_code_paths/test1", "/extra_code_paths/test2"]'
  healthcheck:
    test: "amoc status"

services:
  amoc-master:
    <<: *amoc-defaults
    hostname: "amoc-master"
  amoc-worker-1: &amoc-worker
    <<: *amoc-defaults
    hostname: "amoc-worker-1"
  amoc-worker-2:
    <<: *amoc-defaults
    hostname: "amoc-worker-2"
  amoc-worker-3:
    <<: *amoc-defaults
    hostname: "amoc-worker-3"
networks:
  amoc-test-network:
